import type { F6OptimizationResultV2, F6OptimizationResultV3, F6ReadableOptimizationResult } from "@ai-assist/contracts";

function LegacyF6Summary({ report, selectedWorksheetName }: { readonly report: F6OptimizationResultV2; readonly selectedWorksheetName?: string }) {
  const selected = report.worksheets.find(({ worksheetName }) => worksheetName === selectedWorksheetName);
  return <><div className="f6-summary__header"><div><span>Governed options overview</span><h2>Optimization summary · {report.runStatus}</h2></div><strong>{report.summary.candidateOptionCount} Candidates</strong></div><div className="f6-summary__counts"><span>Worksheets {report.summary.worksheetCount}</span><span>Completed {report.summary.completedWorksheetCount}</span><span>Partial {report.summary.partiallyCompletedWorksheetCount}</span><span>Evidence gaps {report.summary.insufficientEvidenceOptionCount}</span><span>Calculation failed {report.summary.calculationFailedOptionCount}</span></div>{selected === undefined ? null : <div className="f6-option-comparison"><h3>{selected.worksheetName}</h3><div className="f6-baseline"><span>Governed baseline</span><strong>Cpk {selected.baselineMetrics.cpk.toFixed(3)}</strong><span>RSS {selected.baselineMetrics.rssSigma.toFixed(3)}</span><span>DPM {selected.baselineMetrics.dpm.toFixed(2)}</span></div><table><thead><tr><th>Option</th><th>Status</th><th>Cp</th><th>CpkL</th><th>CpkU</th><th>Cpk</th><th>RSS</th><th>DPM</th></tr></thead><tbody>{selected.options.map((option) => <tr key={option.optionId}><td>{option.optionId.split(":").at(-1)}</td><td>{option.status}</td>{option.status === "completed" ? <><td>{option.resultMetrics.cp.toFixed(3)}</td><td>{option.resultMetrics.lowerCpk.toFixed(3)}</td><td>{option.resultMetrics.upperCpk.toFixed(3)}</td><td>{option.resultMetrics.cpk.toFixed(3)}</td><td>{option.resultMetrics.rssSigma.toFixed(3)}</td><td>{option.resultMetrics.dpm.toFixed(2)}</td></> : <td colSpan={6}>Evidence or calculation unavailable</td>}</tr>)}</tbody></table></div>}<table><thead><tr><th>Worksheet</th><th>Status</th><th>Options</th></tr></thead><tbody>{report.worksheets.map((worksheet) => <tr key={worksheet.worksheetName}><td>{worksheet.worksheetName}</td><td>{worksheet.runStatus}</td><td>{worksheet.options.length}</td></tr>)}</tbody></table></>;
}

function SequentialF6Summary({ report, selectedWorksheetName }: { readonly report: F6OptimizationResultV3; readonly selectedWorksheetName?: string }) {
  const selected = report.worksheets.find(({ worksheetName }) => worksheetName === selectedWorksheetName);
  const zh = report.interactionLanguage.uiCatalogLanguage === "zh";
  const labels = zh
    ? { overview: "受控顺序优化", title: "优化摘要", center: "中心评估", contributors: "贡献因子优先级", specifications: "规格变更建议", tolerance: "公差优化", completed: "已完成", completedOptions: "已完成方案", failedOptions: "失败方案", clarification: "需要澄清", none: "无规格变更建议", noTolerance: "能力满足目标，无需内置公差方案", approval: "需要工程审批" }
    : { overview: "Governed sequential optimization", title: "Optimization summary", center: "Center assessment", contributors: "Contributor priorities", specifications: "Specification changes", tolerance: "Tolerance optimization", completed: "Completed", completedOptions: "Completed options", failedOptions: "Failed options", clarification: "Clarification required", none: "No specification change proposed", noTolerance: "Capability meets target; no built-in tolerance option required", approval: "Engineering approval required" };
  const tolerance = selected?.steps[3];
  return <><div className="f6-summary__header"><div><span>{labels.overview}</span><h2>{labels.title} · {report.runStatus}</h2></div><strong>{report.summary.worksheetCount} Worksheets</strong></div><div className="f6-summary__counts"><span>{labels.completed} {report.summary.completedWorksheetCount}</span><span>{labels.clarification} {report.summary.clarificationRequiredWorksheetCount}</span><span>{report.summary.completedOptionCount} {labels.completedOptions}</span><span>{report.summary.calculationFailedOptionCount} {labels.failedOptions}</span></div>{selected === undefined ? null : <div className="f6-option-comparison"><h3>{selected.worksheetName}</h3><ol className="f6-sequential-steps"><li><h4>{labels.center}</h4><p>{selected.steps[0].status}</p>{selected.steps[0].status === "offset" ? <p>{selected.steps[0].interpretation}</p> : null}</li><li><h4>{labels.contributors}</h4><table><thead><tr><th>Rank</th><th>Factor</th><th>Priority</th><th>Guidance</th></tr></thead><tbody>{selected.steps[1].priorities.map((priority) => <tr key={`${priority.rank}:${priority.factor.factorName}`}><td>{priority.rank}</td><td>{priority.factor.factorName}</td><td>{priority.rank === 1 ? "High" : "Lower"}</td><td>{priority.guidance}</td></tr>)}</tbody></table></li><li><h4>{labels.specifications}</h4>{selected.steps[2].proposals.length === 0 ? <p>{labels.none}</p> : <table><thead><tr><th>Side</th><th>Current</th><th>Proposed</th><th>Target Cpk</th><th>Approval</th></tr></thead><tbody>{selected.steps[2].proposals.map((proposal) => <tr key={proposal.side}><td>{proposal.side}</td><td>{proposal.currentLimit}</td><td>{proposal.proposedLimit}</td><td>{proposal.targetCpk}</td><td>{labels.approval}</td></tr>)}</tbody></table>}{selected.steps[2].clarifications.map((item) => <p key={item.reasonCode}>{labels.clarification}: {item.reasonCode}</p>)}</li><li><h4>{labels.tolerance}</h4>{tolerance.options.length === 0 ? <p>{labels.noTolerance}</p> : <table><thead><tr><th>Option</th><th>Factors</th><th>Reduction</th><th>Status</th><th>Cpk</th></tr></thead><tbody>{tolerance.options.map((option) => <tr key={option.optionCode}><td>{option.optionCode}</td><td>{option.reductions.map(({ factor }) => factor.factorName).join(", ")}</td><td>{option.reductionRatios.map((ratio) => `${(ratio * 100).toFixed(1)}%`).join(", ")}</td><td>{option.status}</td><td>{option.status === "completed" ? option.resultMetrics.cpk.toFixed(3) : "N/A"}</td></tr>)}</tbody></table>}</li></ol></div>}<table><thead><tr><th>Worksheet</th><th>Status</th></tr></thead><tbody>{report.worksheets.map((worksheet) => <tr key={worksheet.worksheetName}><td>{worksheet.worksheetName}</td><td>{worksheet.runStatus}</td></tr>)}</tbody></table></>;
}

export function F6Summary({ report, selectedWorksheetName }: { readonly report?: F6ReadableOptimizationResult; readonly selectedWorksheetName?: string }) {
  if (report === undefined) return null;
  return <section className="f6-summary" aria-label="Optimization summary">{report.optimizationVersion === "f6-optimization-v3"
    ? <SequentialF6Summary report={report} {...(selectedWorksheetName === undefined ? {} : { selectedWorksheetName })} />
    : <LegacyF6Summary report={report} {...(selectedWorksheetName === undefined ? {} : { selectedWorksheetName })} />}</section>;
}
